// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc_stuff/schema.proto

package grpc_stuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServeCacheClient is the client API for ServeCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServeCacheClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Empty, error)
	SetDefault(ctx context.Context, in *SetDefaultRequest, opts ...grpc.CallOption) (*Empty, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error)
	Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetWithExpiration(ctx context.Context, in *GetWithExpirationRequest, opts ...grpc.CallOption) (*GetWithExpirationResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteExpired(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Items(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemsResponse, error)
}

type serveCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewServeCacheClient(cc grpc.ClientConnInterface) ServeCacheClient {
	return &serveCacheClient{cc}
}

func (c *serveCacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) SetDefault(ctx context.Context, in *SetDefaultRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/SetDefault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Replace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) GetWithExpiration(ctx context.Context, in *GetWithExpirationRequest, opts ...grpc.CallOption) (*GetWithExpirationResponse, error) {
	out := new(GetWithExpirationResponse)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/GetWithExpiration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) DeleteExpired(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/DeleteExpired", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Items(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemsResponse, error) {
	out := new(ItemsResponse)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Items", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServeCacheServer is the server API for ServeCache service.
// All implementations must embed UnimplementedServeCacheServer
// for forward compatibility
type ServeCacheServer interface {
	Set(context.Context, *SetRequest) (*Empty, error)
	SetDefault(context.Context, *SetDefaultRequest) (*Empty, error)
	Add(context.Context, *AddRequest) (*Empty, error)
	Replace(context.Context, *ReplaceRequest) (*Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetWithExpiration(context.Context, *GetWithExpirationRequest) (*GetWithExpirationResponse, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
	DeleteExpired(context.Context, *Empty) (*Empty, error)
	Items(context.Context, *Empty) (*ItemsResponse, error)
	mustEmbedUnimplementedServeCacheServer()
}

// UnimplementedServeCacheServer must be embedded to have forward compatible implementations.
type UnimplementedServeCacheServer struct {
}

func (UnimplementedServeCacheServer) Set(context.Context, *SetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedServeCacheServer) SetDefault(context.Context, *SetDefaultRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefault not implemented")
}
func (UnimplementedServeCacheServer) Add(context.Context, *AddRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedServeCacheServer) Replace(context.Context, *ReplaceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replace not implemented")
}
func (UnimplementedServeCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServeCacheServer) GetWithExpiration(context.Context, *GetWithExpirationRequest) (*GetWithExpirationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithExpiration not implemented")
}
func (UnimplementedServeCacheServer) Delete(context.Context, *DeleteRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedServeCacheServer) DeleteExpired(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpired not implemented")
}
func (UnimplementedServeCacheServer) Items(context.Context, *Empty) (*ItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Items not implemented")
}
func (UnimplementedServeCacheServer) mustEmbedUnimplementedServeCacheServer() {}

// UnsafeServeCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServeCacheServer will
// result in compilation errors.
type UnsafeServeCacheServer interface {
	mustEmbedUnimplementedServeCacheServer()
}

func RegisterServeCacheServer(s grpc.ServiceRegistrar, srv ServeCacheServer) {
	s.RegisterService(&ServeCache_ServiceDesc, srv)
}

func _ServeCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_SetDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).SetDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/SetDefault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).SetDefault(ctx, req.(*SetDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Replace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Replace(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_GetWithExpiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithExpirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).GetWithExpiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/GetWithExpiration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).GetWithExpiration(ctx, req.(*GetWithExpirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_DeleteExpired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).DeleteExpired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/DeleteExpired",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).DeleteExpired(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Items_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Items(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Items",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Items(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServeCache_ServiceDesc is the grpc.ServiceDesc for ServeCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServeCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.ServeCache",
	HandlerType: (*ServeCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ServeCache_Set_Handler,
		},
		{
			MethodName: "SetDefault",
			Handler:    _ServeCache_SetDefault_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _ServeCache_Add_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _ServeCache_Replace_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ServeCache_Get_Handler,
		},
		{
			MethodName: "GetWithExpiration",
			Handler:    _ServeCache_GetWithExpiration_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServeCache_Delete_Handler,
		},
		{
			MethodName: "DeleteExpired",
			Handler:    _ServeCache_DeleteExpired_Handler,
		},
		{
			MethodName: "Items",
			Handler:    _ServeCache_Items_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_stuff/schema.proto",
}
