// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc_stuff/schema.proto

package grpc_stuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServeCacheClient is the client API for ServeCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServeCacheClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type serveCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewServeCacheClient(cc grpc.ClientConnInterface) ServeCacheClient {
	return &serveCacheClient{cc}
}

func (c *serveCacheClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/cache.ServeCache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServeCacheServer is the server API for ServeCache service.
// All implementations must embed UnimplementedServeCacheServer
// for forward compatibility
type ServeCacheServer interface {
	Insert(context.Context, *InsertRequest) (*Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedServeCacheServer()
}

// UnimplementedServeCacheServer must be embedded to have forward compatible implementations.
type UnimplementedServeCacheServer struct {
}

func (UnimplementedServeCacheServer) Insert(context.Context, *InsertRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedServeCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServeCacheServer) mustEmbedUnimplementedServeCacheServer() {}

// UnsafeServeCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServeCacheServer will
// result in compilation errors.
type UnsafeServeCacheServer interface {
	mustEmbedUnimplementedServeCacheServer()
}

func RegisterServeCacheServer(s grpc.ServiceRegistrar, srv ServeCacheServer) {
	s.RegisterService(&ServeCache_ServiceDesc, srv)
}

func _ServeCache_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.ServeCache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServeCache_ServiceDesc is the grpc.ServiceDesc for ServeCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServeCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.ServeCache",
	HandlerType: (*ServeCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _ServeCache_Insert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ServeCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_stuff/schema.proto",
}
